version: "3.7"
services:
  app:
    # build: .
    image: ghcr.io/sondregronas/feideutstyrbase:latest
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      # - ./responsibility.html:/app/templates/user/responsibility.html
      # - ./overrides:/overrides  # Optional, such as custom templates or static files
      #                             (i.e.) ./logo.png:/overrides/static/logo.png
      #                             or passing an entire directory, follows the same structure as the app directory
      #                             (you might want to override /templates/user/globals.html to add templating variables)
    environment:
      # Feide client settings (Get from https://dashboard.dataporten.no)
      # FEIDE_REDIRECT_URI must be set to <fqdn>/login/feide/callback in dataporten
      - FEIDE_REDIRECT_URI=https://<fqdn>/login/feide/callback
      - FEIDE_CLIENT_ID=
      - FEIDE_CLIENT_SECRET=

      # Label server FQDN (https://github.com/VaagenIM/EtikettServer)
      - LABEL_SERVER=https://<fqdn-label>

      # Global settings
      - MAX_DAYS=14 # Maximum days equipment can be borrowed
      - MAX_LABELS=10 # Maximum number of labels that can be printed at a time

      # Teams Webhooks (for sending notifications to teams channel) - comma separated
      - TEAMS_WEBHOOKS=
      - TEAMS_WEBHOOKS_DEVIATIONS=

      # Reverse proxy for kiosk mode (No login, all visitors are administrators
      # If you don't know what this is, leave it blank
      # Ensure access list only allows your kiosk client, or you will have a bad time
      - KIOSK_FQDN=

      # Misc
      - DEBUG=False        # Don't use debug mode in production (only responds to "True")
      - WEB_CONCURRENCY=4  # Number of workers for gunicorn (default 1)
      - AUTO_UPDATE=True   # Automatically update app on startup (default True) (only responds to "True")

      # API Token (for API access, see documentation for endpoints, send automatic reports etc)
      - API_TOKEN=

      # Set timezone to your local timezone
      - TZ=Europe/Oslo
    restart: unless-stopped