name: Demo

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ main ]
    types:
      - completed

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  demo:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Set Timezone to Europe/Oslo
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Europe/Oslo"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # TODO: Add documentation (mkdocs) build step here

      - name: Run Demobuilder
        run: |
          python .github/demobuilder.py

      - name: Copy Static Files
        run: |
          cp -r BookingSystem/static/* ./demo

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v1
        with:
          artifact-name: github-pages
          path: ./demo

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
